### ISSUE TITLE
Add unblocking dispatch that runs in background

### ISSUE THREAD

**Issue by tokarenko** [artisanofcode/python-banshee#101]
## Description
I suggest to add middleware that dispatches in background and does not block a caller (does not require to 'await' for results).

## Context
This may be useful when dispatching from the DDD repository as described in [The UoW Publishes Events to the Message Bus](https://www.cosmicpython.com/book/chapter_08_events_and_message_bus.html#_option_3_the_uow_publishes_events_to_the_message_bus). This allows to commit a repository transaction and proceed further relying on eventual consistency.

## Possible implementation
Consider using threading or [asyncio.create_task](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.create_task)

**Comment by danielknell** [comment]
I think this use-case should hopefully be covered by #1. I've made some progress there, but its a complex piece and I've not had a great deal of free time to work on it.

Inital focus will be on having channels for processing things in a seperate worker processes but I cant see why there would be anything stopping the worker from running inside the main process.

**Comment by danielknell** [comment]
If your goal is to release the execution in a handler, then the [Handle After](https://banshee.artisan.io/middleware/handle-after/) middleware should work, which will not return on the root call to the bus, but will return immediately from the new handle call, and defer processing the message until after the current handler has finished.

**Comment by tokarenko** [comment]
Thank you @danielknell for your quick reply. I think that the ‘Handle After’ will suffice for my use case. Will try it soon.
By the way, I have been using the Banshee for about a year, and I am very satisfied with the design, flexibility and code quality. You have been doing a great job!
